### ISSUE TITLE
Cloning Functionality not correct

### ISSUE THREAD

**Issue by lonfee88** [PatrickMurphy/absorb#1]
When I set clone=true, the object1 is changed still

obj1 = { foo: 123, bar: 456 };
obj3 = absorb(obj1, obj2, true);

Actual:
console.log(obj1); // Output: { foo: 123, bar: 123, **key: 'value'** }
console.log(obj3); // Output: { foo: 123, bar: 123, key: 'value' }

Expected: 
console.log(obj1); // Output: { foo: 123, bar: 123}
console.log(obj3); // Output: { foo: 123, bar: 123, key: 'value' }

**Comment by PatrickMurphy** [comment]
Hey! Thanks a lot for pointing out this issue and using my package! If you find any more problems I am happy to fix them!
I had incorrectly cloned the object, I fixed it and just published the package so go ahead and update it to version 1.0.1!

Thanks again!
- Patrick
